security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ETUDIANT:       ROLE_ETUDIANT
        ROLE_ENSEIGNANT:       ROLE_ENSEIGNANT
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /index



            logout:
                path:   /logout
                target: /login
            anonymous:    true
            remember_me:
               key:      "%secret%"
               lifetime: 31536000 # 365 jours en secondes
               path:     /
               domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/Etudiant/, role: ROLE_ETUDIANT }