club:
    path:     /
    defaults: { _controller: "ScolariteAdminBundle:Club:index" }

club_show:
    path:     /{id}/show
    defaults: { _controller: "ScolariteAdminBundle:Club:show" }

club_new:
    path:     /new
    defaults: { _controller: "ScolariteAdminBundle:Club:new" }

club_create:
    path:     /create
    defaults: { _controller: "ScolariteAdminBundle:Club:create" }
    requirements: { _method: post }

club_edit:
    path:     /{id}/edit
    defaults: { _controller: "ScolariteAdminBundle:Club:edit" }

club_update:
    path:     /{id}/update
    defaults: { _controller: "ScolariteAdminBundle:Club:update" }
    requirements: { _method: post|put }

club_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScolariteAdminBundle:Club:delete" }
    requirements: { _method: post|delete }
