emploi:
    path:     /
    defaults: { _controller: "ScolariteAdminBundle:Emploi:index" }

emploi_show:
    path:     /{id}/show
    defaults: { _controller: "ScolariteAdminBundle:Emploi:show" }

emploi_new:
    path:     /new
    defaults: { _controller: "ScolariteAdminBundle:Emploi:new" }

emploi_create:
    path:     /create
    defaults: { _controller: "ScolariteAdminBundle:Emploi:create" }
    requirements: { _method: post }

emploi_edit:
    path:     /{id}/edit
    defaults: { _controller: "ScolariteAdminBundle:Emploi:edit" }

emploi_update:
    path:     /{id}/update
    defaults: { _controller: "ScolariteAdminBundle:Emploi:update" }
    requirements: { _method: post|put }

emploi_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScolariteAdminBundle:Emploi:delete" }
    requirements: { _method: post|delete }
