salle:
    path:     /
    defaults: { _controller: "ScolariteAdminBundle:Salle:index" }

salle_show:
    path:     /{id}/show
    defaults: { _controller: "ScolariteAdminBundle:Salle:show" }

salle_new:
    path:     /new
    defaults: { _controller: "ScolariteAdminBundle:Salle:new" }

salle_create:
    path:     /create
    defaults: { _controller: "ScolariteAdminBundle:Salle:create" }
    requirements: { _method: post }

salle_edit:
    path:     /{id}/edit
    defaults: { _controller: "ScolariteAdminBundle:Salle:edit" }

salle_update:
    path:     /{id}/update
    defaults: { _controller: "ScolariteAdminBundle:Salle:update" }
    requirements: { _method: post|put }

salle_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScolariteAdminBundle:Salle:delete" }
    requirements: { _method: post|delete }
