test:
    path:     /
    defaults: { _controller: "ScolariteAdminBundle:Test:index" }

test_show:
    path:     /{id}/show
    defaults: { _controller: "ScolariteAdminBundle:Test:show" }

test_new:
    path:     /new
    defaults: { _controller: "ScolariteAdminBundle:Test:new" }

test_create:
    path:     /create
    defaults: { _controller: "ScolariteAdminBundle:Test:create" }
    requirements: { _method: post }

test_edit:
    path:     /{id}/edit
    defaults: { _controller: "ScolariteAdminBundle:Test:edit" }

test_update:
    path:     /{id}/update
    defaults: { _controller: "ScolariteAdminBundle:Test:update" }
    requirements: { _method: post|put }

test_delete:
    path:     /{id}/delete
    defaults: { _controller: "ScolariteAdminBundle:Test:delete" }
    requirements: { _method: post|delete }
